# Generated by Django 3.2.13 on 2022-04-19 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_redmine', models.IntegerField(verbose_name='ID для Redmine')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включено')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VacationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_finish', models.DateField(verbose_name='Дата конца')),
                ('reason', models.CharField(max_length=150, verbose_name='Причина')),
                ('imployee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imployee.imployee', verbose_name='сотрудник')),
            ],
        ),
    ]
